site_name: Igor's Knowledge Base
site_description: A collection of software engineering knowledge and tips
site_author: Igor Souza
site_url: https://igormcsouza.github.io/knowledge-base/

repo_name: igormcsouza/knowledge-base
repo_url: https://github.com/igormcsouza/knowledge-base

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Python:
      - Tips & Tricks: python-tips.md
      - Flask Framework: python-flask-framework.md
  - Git:
      - Tricks & Commands: git-tricks.md
      - Configurations: git-configurations.md
  - Tags: tags.md